-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.budget_ceiling
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    ceiling_amount bigint,
    code character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    end_year integer,
    start_year integer,
    tier integer,
    used_amount bigint,
    parent_id bigint,
    CONSTRAINT budget_ceiling_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.budget_ceiling_limit
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    amount numeric(19, 2) NOT NULL,
    end_year integer NOT NULL,
    geo_location_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    start_year integer NOT NULL,
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    type_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    used_amount numeric(19, 2) NOT NULL,
    geo_location_type character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT budget_ceiling_limit_pkey PRIMARY KEY (id),
    CONSTRAINT uk8d52coes5qdmpnqxtpp69lxv0 UNIQUE (type, type_code, geo_location_code, start_year, end_year),
    CONSTRAINT ukr8jvm7jgqvo42ts4pwilya983 UNIQUE (type, type_code, geo_location_type, geo_location_code, start_year, end_year)
);

CREATE TABLE IF NOT EXISTS public.budget_mof_ceiling_limit
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    amount numeric(19, 2) NOT NULL,
    category character varying(255) COLLATE pg_catalog."default" NOT NULL,
    end_year integer NOT NULL,
    start_year integer NOT NULL,
    used_amount numeric(19, 2) NOT NULL,
    CONSTRAINT budget_mof_ceiling_limit_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.budgetcoa
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    coa_code character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    is_active boolean NOT NULL,
    coa_economics_id uuid NOT NULL,
    coa_fund_id uuid NOT NULL,
    coa_geo_location_id uuid NOT NULL,
    coa_organization_id uuid NOT NULL,
    coa_program_id uuid NOT NULL,
    coa_project_id uuid NOT NULL,
    CONSTRAINT budgetcoa_pkey PRIMARY KEY (id),
    CONSTRAINT ukc6bcunaijekilf8mvr101d05 UNIQUE (coa_code)
);

CREATE TABLE IF NOT EXISTS public.coa
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    coa_code character varying(200) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    is_active boolean NOT NULL,
    coa_economics_id uuid,
    coa_fund_id uuid,
    coa_project_id uuid,
    coa_geo_location_id uuid,
    coa_organization_id uuid NOT NULL,
    coa_program_id uuid,
    CONSTRAINT coa_pkey PRIMARY KEY (id),
    CONSTRAINT ukkd2r0k41x0p4j4dg8vmiw3kxy UNIQUE (coa_code)
);

CREATE TABLE IF NOT EXISTS public.coa_activity
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    activity_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    activity_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    activity_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean,
    sub_program_id uuid NOT NULL,
    CONSTRAINT coa_activity_pkey PRIMARY KEY (id),
    CONSTRAINT uk7lwn4c96ten5off85t8eig0m8 UNIQUE (id, sub_program_id)
);

CREATE TABLE IF NOT EXISTS public.coa_approved_fund
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    approved_fund_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    approved_fund_name character varying(100) COLLATE pg_catalog."default",
    approved_fund_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean,
    fund_sub_type_id uuid NOT NULL,
    CONSTRAINT coa_approved_fund_pkey PRIMARY KEY (id),
    CONSTRAINT ukcarvmsxup0vxm7q4c90aj507l UNIQUE (id, fund_sub_type_id)
);

CREATE TABLE IF NOT EXISTS public.coa_component
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    component_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    component_name character varying(100) COLLATE pg_catalog."default",
    component_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean,
    approved_fund_id uuid NOT NULL,
    CONSTRAINT coa_component_pkey PRIMARY KEY (id),
    CONSTRAINT uki6y1e5expsxwti7f1ynjxbryr UNIQUE (id, approved_fund_id)
);

CREATE TABLE IF NOT EXISTS public.coa_economics
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    is_active boolean,
    level1_id uuid,
    level2_id uuid,
    level3_id uuid,
    level4_id uuid,
    level5_id uuid,
    level6_id uuid,
    CONSTRAINT coa_economics_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coa_fund
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    is_active boolean,
    approved_fund_id uuid,
    component_id uuid,
    fund_sub_type_id uuid,
    fund_type_id uuid NOT NULL,
    CONSTRAINT coa_fund_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coa_fund_sub_type
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    fund_sub_type_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    fund_sub_type_name character varying(100) COLLATE pg_catalog."default",
    fund_sub_type_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean,
    fund_type_id uuid NOT NULL,
    CONSTRAINT coa_fund_sub_type_pkey PRIMARY KEY (id),
    CONSTRAINT uk2n1etut8anftrs9s1d1bqmgv6 UNIQUE (id, fund_type_id)
);

CREATE TABLE IF NOT EXISTS public.coa_fund_type
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    fund_type_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    fund_type_name character varying(100) COLLATE pg_catalog."default",
    fund_type_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean,
    CONSTRAINT coa_fund_type_pkey PRIMARY KEY (id),
    CONSTRAINT uk1wcjxcj4omx7gjcbrqfkgcnrk UNIQUE (fund_type_code)
);

CREATE TABLE IF NOT EXISTS public.coa_level1
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    level1_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    level1_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    level1_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT coa_level1_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coa_level2
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    level2_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    level2_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    level2_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    level1_id uuid NOT NULL,
    CONSTRAINT coa_level2_pkey PRIMARY KEY (id),
    CONSTRAINT uk1n8elck7u03kg8flkjhsyp2un UNIQUE (id, level1_id)
);

CREATE TABLE IF NOT EXISTS public.coa_level3
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    level3_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    level3_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    level3_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    level2_id uuid NOT NULL,
    CONSTRAINT coa_level3_pkey PRIMARY KEY (id),
    CONSTRAINT ukdo0kjyyye9a3b4jw7a7qgtupy UNIQUE (id, level2_id)
);

CREATE TABLE IF NOT EXISTS public.coa_level4
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    level4_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    level4_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    level4_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    level3_id uuid NOT NULL,
    CONSTRAINT coa_level4_pkey PRIMARY KEY (id),
    CONSTRAINT uk259uryvu6521lgh3u4s5jfq32 UNIQUE (id, level3_id)
);

CREATE TABLE IF NOT EXISTS public.coa_level5
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    level5_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    level5_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    level5_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    level4_id uuid NOT NULL,
    CONSTRAINT coa_level5_pkey PRIMARY KEY (id),
    CONSTRAINT uk6457goh7g19yjgsld293nclhx UNIQUE (id, level4_id)
);

CREATE TABLE IF NOT EXISTS public.coa_level6
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    level6_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    level6_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    level6_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    level5_id uuid NOT NULL,
    CONSTRAINT coa_level6_pkey PRIMARY KEY (id),
    CONSTRAINT uk4614ilii6yvqr52w8h8yashkg UNIQUE (id, level5_id)
);

CREATE TABLE IF NOT EXISTS public.coa_nature_of_project
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    nature_of_project_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nature_of_project_name character varying(100) COLLATE pg_catalog."default",
    nature_of_project_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    project_start_year_id uuid NOT NULL,
    CONSTRAINT coa_nature_of_project_pkey PRIMARY KEY (id),
    CONSTRAINT ukhtik2x8n6p17nt0nl7i4h1jat UNIQUE (id, project_start_year_id)
);

CREATE TABLE IF NOT EXISTS public.coa_organization
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    organization_code character varying(255) COLLATE pg_catalog."default",
    orgination_description character varying(255) COLLATE pg_catalog."default",
    district_id uuid,
    level_of_government_id uuid,
    orgination_entity_id uuid,
    province_id uuid,
    province_dept_id uuid,
    province_dept_division_id uuid,
    province_workunit_id uuid,
    sub_district_id uuid,
    village_id uuid,
    CONSTRAINT coa_organization_pkey PRIMARY KEY (id),
    CONSTRAINT ukcqls1sfvq20seg8nnc6445d5y UNIQUE (organization_code)
);

CREATE TABLE IF NOT EXISTS public.coa_organization_assignment
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    admin_id character varying(255) COLLATE pg_catalog."default",
    coa_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    is_active boolean NOT NULL,
    coa_organization_id uuid NOT NULL,
    CONSTRAINT coa_organization_assignment_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coa_program
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    program_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    program_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    program_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT coa_program_pkey PRIMARY KEY (id),
    CONSTRAINT uk511m21o7fh1ejkvmexily9okv UNIQUE (program_code)
);

CREATE TABLE IF NOT EXISTS public.coa_project
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    code character varying(255) COLLATE pg_catalog."default",
    description character varying(255) COLLATE pg_catalog."default",
    is_active boolean,
    nature_of_project_id uuid,
    project_start_year_id uuid,
    project_sub_type_id uuid,
    project_type_id uuid NOT NULL,
    project_sequence_id uuid,
    CONSTRAINT coa_project_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.coa_project_sequence
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    project_sequence__code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    project_sequence_name character varying(100) COLLATE pg_catalog."default",
    project_sequence_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    nature_of_project_id uuid NOT NULL,
    CONSTRAINT coa_project_sequence_pkey PRIMARY KEY (id),
    CONSTRAINT uk5hgtnsex3serv4xk20cguswe UNIQUE (id, nature_of_project_id)
);

CREATE TABLE IF NOT EXISTS public.coa_project_start_year
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    project_start_year_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    project_start_year_name character varying(100) COLLATE pg_catalog."default",
    project_start_year_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    project_sub_type_id uuid NOT NULL,
    CONSTRAINT coa_project_start_year_pkey PRIMARY KEY (id),
    CONSTRAINT uk571in3lr873xunjsg4x4xjlar UNIQUE (id, project_sub_type_id)
);

CREATE TABLE IF NOT EXISTS public.coa_project_sub_type
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    project_sub_type_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    project_sub_type_name character varying(100) COLLATE pg_catalog."default",
    project_sub_type_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    project_type_id uuid NOT NULL,
    CONSTRAINT coa_project_sub_type_pkey PRIMARY KEY (id),
    CONSTRAINT ukof1sol4evbms88o8h3otyxu9v UNIQUE (id, project_type_id)
);

CREATE TABLE IF NOT EXISTS public.coa_project_type
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    project_type_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    project_type_name character varying(100) COLLATE pg_catalog."default",
    project_type_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT coa_project_type_pkey PRIMARY KEY (id),
    CONSTRAINT uk5f769rcguvkyaw1cnowpjb30e UNIQUE (project_type_code)
);

CREATE TABLE IF NOT EXISTS public.coa_segment_program
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    coa_program_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(255) COLLATE pg_catalog."default",
    is_active boolean,
    program_id uuid,
    sub_program_id uuid,
    CONSTRAINT coa_segment_program_pkey PRIMARY KEY (id),
    CONSTRAINT ukslj0bys849g9jftt76ndu4jcw UNIQUE (coa_program_code)
);

CREATE TABLE IF NOT EXISTS public.coa_sub_program
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    sub_program_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    sub_program_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    sub_program_unique_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    program_id uuid NOT NULL,
    CONSTRAINT coa_sub_program_pkey PRIMARY KEY (id),
    CONSTRAINT ukqnkbf7qreylrbpg3iyhakh5dx UNIQUE (id, program_id)
);

CREATE TABLE IF NOT EXISTS public.department
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    department_code character varying(2) COLLATE pg_catalog."default" NOT NULL,
    department_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    department_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean,
    district_id uuid NOT NULL,
    organisation_id uuid NOT NULL,
    CONSTRAINT department_pkey PRIMARY KEY (id),
    CONSTRAINT uq_department_code_per_district UNIQUE (district_id, department_code),
    CONSTRAINT uq_department_id UNIQUE (department_id)
);

CREATE TABLE IF NOT EXISTS public.department_division
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    division_code character varying(2) COLLATE pg_catalog."default" NOT NULL,
    division_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    division_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean,
    department_id uuid NOT NULL,
    CONSTRAINT department_division_pkey PRIMARY KEY (id),
    CONSTRAINT uq_division_code_per_department UNIQUE (department_id, division_code),
    CONSTRAINT uq_division_id UNIQUE (division_id)
);

CREATE TABLE IF NOT EXISTS public.district
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    district_code character varying(2) COLLATE pg_catalog."default" NOT NULL,
    district_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean,
    province_id uuid NOT NULL,
    CONSTRAINT district_pkey PRIMARY KEY (id),
    CONSTRAINT uklba80ep09m4gcltg9mbbuleao UNIQUE (district_id),
    CONSTRAINT uq_district_code_per_province UNIQUE (province_id, district_code)
);

CREATE TABLE IF NOT EXISTS public.geo_location
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    geo_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    geo_description character varying(255) COLLATE pg_catalog."default",
    is_active boolean,
    district_id uuid,
    province_id uuid NOT NULL,
    sub_district_id uuid,
    village_id uuid,
    CONSTRAINT geo_location_pkey PRIMARY KEY (id),
    CONSTRAINT uknh37hyaalxkjd9lj94xs4paw0 UNIQUE (geo_code)
);

CREATE TABLE IF NOT EXISTS public.level_of_government
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    level_of_government_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    level_of_government_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT level_of_government_pkey PRIMARY KEY (id),
    CONSTRAINT uk48ioe40claxxakjwuerm0vrt1 UNIQUE (level_of_government_name),
    CONSTRAINT uklld0jou0wiikq56lowr9babd9 UNIQUE (level_of_government_code)
);

CREATE TABLE IF NOT EXISTS public.orgination_entity
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    orgination_entity_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    orgination_entity_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT orgination_entity_pkey PRIMARY KEY (id),
    CONSTRAINT uk85pgnvxvwbawnyiygse2twybk UNIQUE (orgination_entity_name),
    CONSTRAINT ukd3oknn1e1idf78adx17882xx1 UNIQUE (orgination_entity_code)
);

CREATE TABLE IF NOT EXISTS public.province
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    province_code character varying(2) COLLATE pg_catalog."default" NOT NULL,
    province_id character varying(3) COLLATE pg_catalog."default" NOT NULL,
    province_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT province_pkey PRIMARY KEY (id),
    CONSTRAINT ukffhr8sy2c2yk6qu2f9ivrinv3 UNIQUE (province_code),
    CONSTRAINT ukmcbr0n641yap7a60ffh2ojnc0 UNIQUE (province_id)
);

CREATE TABLE IF NOT EXISTS public.province_department
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    province_dept_code character varying(2) COLLATE pg_catalog."default" NOT NULL,
    province_dept_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    province_dept_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    province_id uuid NOT NULL,
    organisation_id uuid,
    CONSTRAINT province_department_pkey PRIMARY KEY (id),
    CONSTRAINT uq_department_code_per_province UNIQUE (province_id, province_dept_code),
    CONSTRAINT uq_province_dept_id UNIQUE (province_dept_id)
);

CREATE TABLE IF NOT EXISTS public.province_department_division
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    province_deptdivision_code character varying(2) COLLATE pg_catalog."default" NOT NULL,
    province_deptdivision_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    province_deptdivision_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    province_dept_id uuid NOT NULL,
    CONSTRAINT province_department_division_pkey PRIMARY KEY (id),
    CONSTRAINT uq_division_code_per_dept UNIQUE (province_dept_id, province_deptdivision_code),
    CONSTRAINT uq_province_deptdivision_id UNIQUE (province_deptdivision_id)
);

CREATE TABLE IF NOT EXISTS public.province_work_unit
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    province_workunit_code character varying(2) COLLATE pg_catalog."default" NOT NULL,
    province_workunit_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    province_workunit_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    province_dept_division_id uuid NOT NULL,
    CONSTRAINT province_work_unit_pkey PRIMARY KEY (id),
    CONSTRAINT uq_province_workunit_id UNIQUE (province_workunit_id),
    CONSTRAINT uq_workunit_code_per_division UNIQUE (province_dept_division_id, province_workunit_code)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.sub_dis_department
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    department_code character varying(2) COLLATE pg_catalog."default" NOT NULL,
    department_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    department_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean,
    sub_district_id uuid NOT NULL,
    CONSTRAINT sub_dis_department_pkey PRIMARY KEY (id),
    CONSTRAINT uq_department_business_id UNIQUE (department_id),
    CONSTRAINT uq_department_code_per_subdistrict UNIQUE (sub_district_id, department_code)
);

CREATE TABLE IF NOT EXISTS public.sub_dis_department_division
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    division_code character varying(2) COLLATE pg_catalog."default" NOT NULL,
    division_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    division_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_active boolean,
    sub_dis_department_id uuid NOT NULL,
    CONSTRAINT sub_dis_department_division_pkey PRIMARY KEY (id),
    CONSTRAINT uq_division_business_id UNIQUE (division_id)
);

CREATE TABLE IF NOT EXISTS public.sub_district
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    sub_district_code character varying(2) COLLATE pg_catalog."default" NOT NULL,
    sub_district_id character varying(20) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    district_id uuid NOT NULL,
    CONSTRAINT sub_district_pkey PRIMARY KEY (id),
    CONSTRAINT uq_subdistrict_business_id UNIQUE (sub_district_id),
    CONSTRAINT uq_subdistrict_code_per_district UNIQUE (district_id, sub_district_code)
);

CREATE TABLE IF NOT EXISTS public.user_access_details
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    description character varying(255) COLLATE pg_catalog."default",
    is_active boolean,
    user_id uuid,
    coa_organization_id uuid,
    village_id uuid,
    CONSTRAINT user_access_details_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_budget_preparation_permission
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    budget_alloc_read boolean,
    budget_alloc_write boolean,
    budget_prep_read boolean,
    budget_prep_write boolean,
    ceiling_read boolean,
    ceiling_write boolean,
    user_id uuid NOT NULL,
    CONSTRAINT user_budget_preparation_permission_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_geo_location_permission
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    district_id uuid NOT NULL,
    geo_location_code character varying(255) COLLATE pg_catalog."default" NOT NULL,
    geo_type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    province_id uuid NOT NULL,
    sub_district_id uuid NOT NULL,
    user_id uuid NOT NULL,
    village_id uuid NOT NULL,
    CONSTRAINT user_geo_location_permission_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    email character varying(255) COLLATE pg_catalog."default",
    enabled boolean NOT NULL,
    password character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.village
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    village_code character varying(3) COLLATE pg_catalog."default" NOT NULL,
    village_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    village_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    sub_district_id uuid NOT NULL,
    CONSTRAINT village_pkey PRIMARY KEY (id),
    CONSTRAINT uq_village_business_id UNIQUE (village_id),
    CONSTRAINT uq_village_code_per_subdistrict UNIQUE (sub_district_id, village_code)
);

CREATE TABLE IF NOT EXISTS public.work_unit
(
    id uuid NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    is_active boolean,
    work_unit_code character varying(3) COLLATE pg_catalog."default" NOT NULL,
    work_unit_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    work_unit_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    sub_dis_department_division_id uuid NOT NULL,
    CONSTRAINT work_unit_pkey PRIMARY KEY (id),
    CONSTRAINT uq_workunit_business_id UNIQUE (work_unit_id)
);

ALTER TABLE IF EXISTS public.budget_ceiling
    ADD CONSTRAINT fkfw805jrw3l2qc2uijtddevsqw FOREIGN KEY (parent_id)
    REFERENCES public.budget_ceiling (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.budgetcoa
    ADD CONSTRAINT fk1loq5sxmyuo6vb8m9qbwtjofg FOREIGN KEY (coa_geo_location_id)
    REFERENCES public.geo_location (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.budgetcoa
    ADD CONSTRAINT fk9r8pck79r4i82ygipvhxjxjc6 FOREIGN KEY (coa_project_id)
    REFERENCES public.coa_project (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.budgetcoa
    ADD CONSTRAINT fk9t6la3b0yclndtkaij4s3460e FOREIGN KEY (coa_economics_id)
    REFERENCES public.coa_economics (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.budgetcoa
    ADD CONSTRAINT fkah59kav21whmqtuwnhkwapq1a FOREIGN KEY (coa_organization_id)
    REFERENCES public.coa_organization (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.budgetcoa
    ADD CONSTRAINT fkhin86ysa3viypsxa1u1ya3fne FOREIGN KEY (coa_fund_id)
    REFERENCES public.coa_fund (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.budgetcoa
    ADD CONSTRAINT fkpdqverrphnx69yrap98nstotf FOREIGN KEY (coa_program_id)
    REFERENCES public.coa_segment_program (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa
    ADD CONSTRAINT fk1a3jhusgr785le0ptgku222a7 FOREIGN KEY (coa_economics_id)
    REFERENCES public.coa_economics (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa
    ADD CONSTRAINT fk4c1awteg993wwpjsf3tvvph6w FOREIGN KEY (coa_fund_id)
    REFERENCES public.coa_fund (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa
    ADD CONSTRAINT fkdldf2kwi52jm2e7ckt97jd4nd FOREIGN KEY (coa_program_id)
    REFERENCES public.coa_segment_program (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa
    ADD CONSTRAINT fkf3bsbtwewgtfseybj4uj9scq9 FOREIGN KEY (coa_project_id)
    REFERENCES public.coa_project (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa
    ADD CONSTRAINT fkpylcgd77e2texxjumuk9v1aqf FOREIGN KEY (coa_organization_id)
    REFERENCES public.coa_organization (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa
    ADD CONSTRAINT fkt855hkkpknxnik3tl708gh7e2 FOREIGN KEY (coa_geo_location_id)
    REFERENCES public.geo_location (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_activity
    ADD CONSTRAINT fk84s2rov07600mtwdsa2rxfu0u FOREIGN KEY (sub_program_id)
    REFERENCES public.coa_sub_program (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_approved_fund
    ADD CONSTRAINT fk3m8m33082mp0n18af8whhj4h2 FOREIGN KEY (fund_sub_type_id)
    REFERENCES public.coa_fund_sub_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_component
    ADD CONSTRAINT fke3eioi7i2ei4o7xucyikkce6w FOREIGN KEY (approved_fund_id)
    REFERENCES public.coa_approved_fund (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_economics
    ADD CONSTRAINT fk4qqrtt5ej7ty73gwcxxfxk5vt FOREIGN KEY (level3_id)
    REFERENCES public.coa_level3 (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_economics
    ADD CONSTRAINT fkfuneuw3se9vhp987vkqcxgn2v FOREIGN KEY (level4_id)
    REFERENCES public.coa_level4 (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_economics
    ADD CONSTRAINT fkhurslqa652h5vtdr1m0oly6qj FOREIGN KEY (level5_id)
    REFERENCES public.coa_level5 (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_economics
    ADD CONSTRAINT fkoes6sqb4qf5nj6b033h0jp2ng FOREIGN KEY (level2_id)
    REFERENCES public.coa_level2 (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_economics
    ADD CONSTRAINT fkoqbgbiluryqfwyo80w8xfu1k FOREIGN KEY (level1_id)
    REFERENCES public.coa_level1 (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_economics
    ADD CONSTRAINT fkt75wk47ledl67viyana7x48th FOREIGN KEY (level6_id)
    REFERENCES public.coa_level6 (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_fund
    ADD CONSTRAINT fk1libmt7sq4lkxu9m194g2p0l FOREIGN KEY (fund_type_id)
    REFERENCES public.coa_fund_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_fund
    ADD CONSTRAINT fkaodblsmcoi27syhfschut0i3l FOREIGN KEY (approved_fund_id)
    REFERENCES public.coa_approved_fund (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_fund
    ADD CONSTRAINT fkeysg986996ofi19e4lg763aof FOREIGN KEY (fund_sub_type_id)
    REFERENCES public.coa_fund_sub_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_fund
    ADD CONSTRAINT fki9etf0t8d7nbky6jy7p7l5mk9 FOREIGN KEY (component_id)
    REFERENCES public.coa_component (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_fund_sub_type
    ADD CONSTRAINT fki7nrgq99l51qqr6xinj64wj7i FOREIGN KEY (fund_type_id)
    REFERENCES public.coa_fund_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_level2
    ADD CONSTRAINT fk5alqjif1njl8puagb89e25j9l FOREIGN KEY (level1_id)
    REFERENCES public.coa_level1 (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_level3
    ADD CONSTRAINT fk5aywuh90ls2ik1vx3csamwrss FOREIGN KEY (level2_id)
    REFERENCES public.coa_level2 (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_level4
    ADD CONSTRAINT fk6wehb4djwd2rj1a9mbegegub3 FOREIGN KEY (level3_id)
    REFERENCES public.coa_level3 (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_level5
    ADD CONSTRAINT fkoat1m20r0ktmfyivpnkk5h44l FOREIGN KEY (level4_id)
    REFERENCES public.coa_level4 (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_level6
    ADD CONSTRAINT fksv9iwp730yq2on7qrqobjgvc1 FOREIGN KEY (level5_id)
    REFERENCES public.coa_level5 (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_nature_of_project
    ADD CONSTRAINT fkkjv40mpegke3bidkos0dqyt21 FOREIGN KEY (project_start_year_id)
    REFERENCES public.coa_project_start_year (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_organization
    ADD CONSTRAINT fk2ryi14hw6barho2n84ple4hj0 FOREIGN KEY (sub_district_id)
    REFERENCES public.sub_district (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_organization
    ADD CONSTRAINT fkaetv2oc9lus0g1hs6tylt4ets FOREIGN KEY (province_workunit_id)
    REFERENCES public.province_work_unit (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_organization
    ADD CONSTRAINT fkd48uyvwius78wukbee3ke140i FOREIGN KEY (province_dept_id)
    REFERENCES public.province_department (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_organization
    ADD CONSTRAINT fkjxhj92h2lwwuv52b9ieq16hnx FOREIGN KEY (province_dept_division_id)
    REFERENCES public.province_department_division (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_organization
    ADD CONSTRAINT fkkwbiee3ggp4700cwuhi6123gc FOREIGN KEY (province_id)
    REFERENCES public.province (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_organization
    ADD CONSTRAINT fklnl8uaoscmdgfxahlr8x1ledv FOREIGN KEY (district_id)
    REFERENCES public.district (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_organization
    ADD CONSTRAINT fkn9ivvj00w2sq4ch48om80ug21 FOREIGN KEY (village_id)
    REFERENCES public.village (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_organization
    ADD CONSTRAINT fkpqsijfxbuv4yl6tsne05sbawh FOREIGN KEY (level_of_government_id)
    REFERENCES public.level_of_government (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_organization
    ADD CONSTRAINT fktoug047ive7wdrhtg43o97803 FOREIGN KEY (orgination_entity_id)
    REFERENCES public.orgination_entity (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_organization_assignment
    ADD CONSTRAINT fkiv7t9wlkeb67miipfnpc1lrpk FOREIGN KEY (coa_organization_id)
    REFERENCES public.coa_organization (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_project
    ADD CONSTRAINT fk8avg87lkj62tu4sxo8s68dol8 FOREIGN KEY (project_sub_type_id)
    REFERENCES public.coa_project_sub_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_project
    ADD CONSTRAINT fk99qy4u6v67j75g98b8bx34v63 FOREIGN KEY (project_type_id)
    REFERENCES public.coa_project_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_project
    ADD CONSTRAINT fken5t8wc468a6oymfd5f17t1c1 FOREIGN KEY (nature_of_project_id)
    REFERENCES public.coa_nature_of_project (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_project
    ADD CONSTRAINT fkjvfhqa33l37h498a6bwdqligc FOREIGN KEY (project_sequence_id)
    REFERENCES public.coa_project_sequence (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_project
    ADD CONSTRAINT fkrqkj45qkqlgw74i0pcnx4yed0 FOREIGN KEY (project_start_year_id)
    REFERENCES public.coa_project_start_year (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_project_sequence
    ADD CONSTRAINT fkdbhdq1a3hqi5v3wqaenekfmnn FOREIGN KEY (nature_of_project_id)
    REFERENCES public.coa_nature_of_project (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_project_start_year
    ADD CONSTRAINT fkfp0tfnfwoaphxxd223q6otbe1 FOREIGN KEY (project_sub_type_id)
    REFERENCES public.coa_project_sub_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_project_sub_type
    ADD CONSTRAINT fk9u87vo1x5ifky3arrao3rl7qc FOREIGN KEY (project_type_id)
    REFERENCES public.coa_project_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_segment_program
    ADD CONSTRAINT fk14j12dpx4flvog39dxqgk5dll FOREIGN KEY (program_id)
    REFERENCES public.coa_program (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_segment_program
    ADD CONSTRAINT fk2jlhonv0a3l53sl2isejvh5tt FOREIGN KEY (sub_program_id)
    REFERENCES public.coa_sub_program (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.coa_sub_program
    ADD CONSTRAINT fk967q2d3qu61l22b51tv90qt4n FOREIGN KEY (program_id)
    REFERENCES public.coa_program (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.department
    ADD CONSTRAINT fk6xjjjt0oyd3yo30k0svyh5i1x FOREIGN KEY (organisation_id)
    REFERENCES public.orgination_entity (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.department
    ADD CONSTRAINT fkq72728gx9gxr45fqhobmowktb FOREIGN KEY (district_id)
    REFERENCES public.district (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.department_division
    ADD CONSTRAINT fkr8r8co3wqgllj5yu0wi981sdg FOREIGN KEY (department_id)
    REFERENCES public.department (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.district
    ADD CONSTRAINT fk276utu38g5lgqeth6pwfm3rw2 FOREIGN KEY (province_id)
    REFERENCES public.province (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.geo_location
    ADD CONSTRAINT fk1gn351a5i2ygnue4h3gt0hnqj FOREIGN KEY (sub_district_id)
    REFERENCES public.sub_district (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.geo_location
    ADD CONSTRAINT fk447sv98kwkescwh7tyqf4loxh FOREIGN KEY (province_id)
    REFERENCES public.province (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.geo_location
    ADD CONSTRAINT fk9sq5fe31kqkbmdj6l7axbss3w FOREIGN KEY (district_id)
    REFERENCES public.district (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.geo_location
    ADD CONSTRAINT fkg6mn5sh666ukspxhjdilvrisq FOREIGN KEY (village_id)
    REFERENCES public.village (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.province_department
    ADD CONSTRAINT fkag5kn07b856awqa7r1lt1fwfx FOREIGN KEY (organisation_id)
    REFERENCES public.orgination_entity (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.province_department
    ADD CONSTRAINT fkeffns37dx5m9afy5ygc289me3 FOREIGN KEY (province_id)
    REFERENCES public.province (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.province_department_division
    ADD CONSTRAINT fkouuqjpx0kyj2tpke6nalpv2i2 FOREIGN KEY (province_dept_id)
    REFERENCES public.province_department (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.province_work_unit
    ADD CONSTRAINT fkh0p5i3wa4immc3vetps8jmedd FOREIGN KEY (province_dept_division_id)
    REFERENCES public.province_department_division (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sub_dis_department
    ADD CONSTRAINT fk7bnd4d7xnmj7knau28gn6c211 FOREIGN KEY (sub_district_id)
    REFERENCES public.sub_district (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sub_dis_department_division
    ADD CONSTRAINT fkcoximo02ljxqjr088ihysrxv5 FOREIGN KEY (sub_dis_department_id)
    REFERENCES public.sub_dis_department (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.sub_district
    ADD CONSTRAINT fklqjwe7n0ji72p33oq5sx00e34 FOREIGN KEY (district_id)
    REFERENCES public.district (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_access_details
    ADD CONSTRAINT fk590pgl3yxtt7x3xer17s16guc FOREIGN KEY (coa_organization_id)
    REFERENCES public.coa_organization (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_access_details
    ADD CONSTRAINT fkd6gaa9eurxo96ju4ukjvfnp5c FOREIGN KEY (village_id)
    REFERENCES public.village (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.village
    ADD CONSTRAINT fk1yit86lqt1ekhtcqh8iafdd7q FOREIGN KEY (sub_district_id)
    REFERENCES public.sub_district (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.work_unit
    ADD CONSTRAINT fkfn27b5ttbsi9bttd2ib9hmxm7 FOREIGN KEY (sub_dis_department_division_id)
    REFERENCES public.sub_dis_department_division (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;